### ISSUE TITLE
Related to Builder's QoL Shaders

### ISSUE THREAD

**Issue by Pho3nixFeath3r** [Builderb0y/AutoCodec#1]
Hey dude, i'm sorry i have to write this thing here, but on ur profile there isn't a page entirely dedicated to ur shaders, so i didn't know how else i could've gotten in touch with u... Anyway i found a bug in ur shaders where slimes spawned on a "normal" y value or in superflat worlds render partially black and this effect worsens when they jump. It's very easy to replicate, just hop on a random seed and spawn a few slimes and u'll see what i mean.

Also since we're at it i have a couple of enhancement requests:
- add either taa or fxaa (not those ones from sildur's shaders or dr desten cause they're both glitchy atm; an alternative could be the one "VanillAA" has or something similar, it's very lightweight and not that effective but it's still better than nothing)
- fix water becoming gradually more green (and coloring ores and blocks the same way) the deeper u go
- remove the annoying screen-filling effect when going into lava, cause it completely nullifies the enhanced vision when submerged in lava that fire resistance potions grant u (especially useful when going on the hunt for ancient debris)

Those things said, have a great saturday night pal!

**Comment by Builderb0y** [comment]
Slimes look normal on my computer. an F3 screenshot might help debug this further. with that said, the only link I have on my modrinth page goes to [discord](https://discord.gg/FMghhxk), which is the preferred place to report bugs for QOL. I'm not sure how you even found this repository when nothing links to it that I'm aware of.

as for the rest of your suggestions, AA in any form is not happening because my eyes aren't good enough to notice it in the first place, which makes it very difficult for me to debug it. water becoming green is an intended feature, and you can tweak this color as desired in `world0/lib/magicNumbers.glsl`. see the readme inside the zip file for more info on how to do that. the lava overlay will be disabled in spectator mode on iris in the next version, but it will stay enabled for all other game modes.

**Comment by Builderb0y** [comment]
...alright then. if you're not going to provide an F3 screenshot then I can't help.
